### ISSUE TITLE
Draw gate on each sample separately

### ISSUE THREAD

**Issue by MikhaelManurung** [DillonHammill/CytoRSuite#16]
Dear Dillon,

Is it possible to draw a gate unique for each sample? I can imagine people (and myself!) would love to do this to accommodate variability due to staining or biological variations. Or perhaps it is possible to implement the gating for a certain group, id, etc.?

Congratulations by the way for making such a great open-source tool! I will definitely spread the word around regarding the package.

**Comment by DillonHammill** [comment]
Hi @bwintang,

Thanks for trying out the package!

Yes this feature is fully supported (but not currently documented) through the `group_by` argument. This argument takes on the names of `pData` variables or variables created with `cyto_annotate`. The data will then be split into groups and you will be guided through drawing a separate gate for each group. 

If you simply want to gate each sample independently you can pass `"name"` to `group_by` as below:

```{r}
# gs is a GatingSet object
gs <- GatingSet(Activation)

# Calling pData on gs will reveal associated experimental variables
pData(gs)

# cyto_annotate provides an interactive interface for adding new variables (excel style)
cyto_annotate(gs)

# These variables can be used to group samples for gating
gate_draw(gs,
                  parent = "root",
                  alias = "Cells",
                  channels = c("FSC-A","SSC-A"),
                  group_by = "name")
```
Supplying multiple grouping variables is also supported. For example if you want to group samples by `Experiment` and `Treatment`, you could add these variables to the GatingSet using `cyto_annotate` and pass both variables to `group_by` as below:

```{r}
gate_draw(gs,
                  parent = "root",
                  alias = "Cells",
                  channels = c("FSC-A","SSC-A"),
                  group_by = c("Experiment","Treatment"))
```
If you need to edit gates for specific groups you can do this with `gate_edit` which will bring up a drop-down menu to ask you which of the groups you would like to edit. Multiple groups can be selected from the menu by holding down the CTRL key.

I will work in some extra documentation to properly demonstrate this feature. There are also a number of additional improvements which will be coming over the next week or so.

Let me know if you encounter any problems.

Dillon

**Comment by MikhaelManurung** [comment]
Dear Dillon,

Thank you for such a prompt reply. I would like to ensure one more thing: during gating of the cells after grouping by, for example, ```donor ID```, are all the samples that belong to that group collapsed for gating or are we merely looking at the first sample in the group?

Are you planning to implement a negative-control-based gating as in this `[link](http://rpubs.com/wjiang2/473129)`?

**Comment by DillonHammill** [comment]
@MikhaelManurung the answer is yes, all the samples in each group will be collapsed for gating. Due to the size of the collapsed data gate_draw will only display the mean number of events per sample (i.e. if there are 10 samples, 1/10 events will be displayed). This sampling behaviour can be controlled through the `display` argument. For example the following will display all events per group and take longer to plot:

```{r}
gate_draw(gs,
    parent = "root",
    alias = "Cells",
    channels = c("FSC-A","SSC-A"),
    display = 1)
```
Negative-control-based gating is also possible through the `select` argument. This argument accepts sample indices to select which samples you would like to use for gating. For example, if your negative control is the first sample in each group:
```{r}
gate_draw(gs,
    parent = "root",
    alias = "Cells",
    channels = c("FSC-A","SSC-A"),
    select = 1)
```
If you want to use a single negative control to gate all your samples a better way would be to use the `overlay` argument. For example, you could extract the data for the negative control and pass this directly to `overlay`. This will overlay the control over the collapsed samples which makes it easy to set gates. See below:
```{r}
# extract data for control sample (assume its the first sample)
Control <- getData(gs, "Live Cells)[[1]]

# pass extracted data to overlay
gate_draw(gs,
    parent = "root",
    alias = "Cells",
    channels = c("FSC-A","SSC-A"),
    overlay = Control)
```
Hope this helps.

Dillon

**Comment by rwbaer** [comment]
@DillonHammill   First, what a great contribution. Kudos.  

I'm still working through things, and despite your answer to this issue, I'm still stuck on whether/how you can do spillover correction if you have a combination of bead standards (stained/unstained bead mixture) for some channels and cell stains for other channels (stain only).   The universal unstained cells would not seem to be appropriate for use in this case, although admittedly, I'm still working through the mechanics going on under the hood..

Any way to do this or sample code available?

**Comment by Biomiha** [comment]
Hi Dillon, 

Is there a way of plotting a fixed number of events (something I've only recently come to understand FlowJo does), rather than a fraction of total events specified with `display`? When using the `cyto_plot_gating_scheme` what happens is that the root population will have a very high number of events making plotting a very intensive operation (this is where `display` is super useful), whereas the last gate will only contain a small fraction (here setting `display` to a low value plots only a handful of events). Alternatively, would there be an option of passing a vector of `display` values - one for each plot, e.g. c(0.01, 0.05, 0.1, 0.5, 1)?

Thanks again. Really enjoying the package. As are my co-workers!

**Comment by DillonHammill** [comment]
Hi @Biomiha,

Glad to hear that you are finding CytoRSuite useful!

I did spend a lot of time playing around with the display options and a percentage works the best. The reasoning for this is to do with overlays and back-gating. CytoRSuite handles the underlying data separately from the overlays. This means that if we set number of events to 5000, this same sampling is applied to the overlay as well. In the case of back-gating this is not desired as it results in over-inflated populations relative to the bottom layer. Instead CytoRSuite selects a proportion of events in the base layer and applies the same sampling to the overlays - thus ensuring that the overlays are not over-inflated. For this reason the display value should be the same within plots.

In terms of `cyto_plot_gating_scheme`, it should be easy to allow users to control the proportion of events to display on a per plot basis. I am working through the entire package to fine tune things and add new features. I will add this to my to-do list so that is feature is available in the next release. This shouldn't be too far away :)

Thanks for the suggestion.

Dillon
