### ISSUE TITLE
Quadrant gate statistics incorrect

### ISSUE THREAD

**Issue by ClaudiaMY** [DillonHammill/CytoRSuite#20]
Hi Dillon,

I've attached a photo of the stats from the quad gate for one of my samples. I just wanted to bring to your attention that the percentages actually don't add up to 100%.

![quad-gate-stats](https://user-images.githubusercontent.com/34495052/67740117-d6df1e00-fa68-11e9-8da7-8fb903fe7a2f.png)

Cheers, 
Claudia

**Comment by DillonHammill** [comment]
Hi Claudia,

Thanks for posting your first issue!

Yes quadrant gate statistics are a known issue with `CytoRSuite` which will be rectified on the next release planned for next week.

The reason for the discrepancy in the statistics is due to the fact that currently `CytoRSuite` uses a series of rectangleGates to to gate these populations. This means that events located on the cross hairs are included in multiple gates, resulting in inaccurate statistics. The fix requires added support for storing quadGate objects in the GatingSet which will be available in `flowWorkspace` on November 1st. These quadGate objects are handled in such a way that cells are assigned to each gate thus preventing overlap and generating more accurate statistics.

I would avoid using quadrant gates in `CytoRSuite` until the new release. Even with considerable overlap the statistics always add to 100% or thereabouts taking into account rounding error.

Here is an example of how the quadrant gates perform in the upcoming release:

![Quadrant Issue](https://user-images.githubusercontent.com/28646736/67740865-700f3400-fa6b-11e9-8dee-b16d00224b18.png)

See RGLab/openCyto#199 and RGLab/cytolib#16 for more details.

Keep an eye out for updates!

Dillon

**Comment by DillonHammill** [comment]
@ClaudiaMY as mentioned earlier the fix for quadrant gate statistics is now implemented in CytoExploreR!

Make sure you have the latest version of the RGLab's cytolib.
